/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BranchWhereUniqueInput } from "../../branch/base/BranchWhereUniqueInput";
import { ValidateNested, IsString, IsOptional, IsDate } from "class-validator";
import { Type } from "class-transformer";
import { EventRegistrationCreateNestedManyWithoutEventsInput } from "./EventRegistrationCreateNestedManyWithoutEventsInput";
import { FeedbackCreateNestedManyWithoutEventsInput } from "./FeedbackCreateNestedManyWithoutEventsInput";

@InputType()
class EventCreateInput {
  @ApiProperty({
    required: true,
    type: () => BranchWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BranchWhereUniqueInput)
  @Field(() => BranchWhereUniqueInput)
  branch!: BranchWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EventRegistrationCreateNestedManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => EventRegistrationCreateNestedManyWithoutEventsInput)
  @IsOptional()
  @Field(() => EventRegistrationCreateNestedManyWithoutEventsInput, {
    nullable: true,
  })
  eventRegistrations?: EventRegistrationCreateNestedManyWithoutEventsInput;

  @ApiProperty({
    required: false,
    type: () => FeedbackCreateNestedManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => FeedbackCreateNestedManyWithoutEventsInput)
  @IsOptional()
  @Field(() => FeedbackCreateNestedManyWithoutEventsInput, {
    nullable: true,
  })
  feedbacks?: FeedbackCreateNestedManyWithoutEventsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  img?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  venue?: string | null;
}

export { EventCreateInput as EventCreateInput };
